### ISSUE TITLE
Bump peerDep to support svelte 5

### ISSUE THREAD

**Issue by mhkeller** [sveltejs/rollup-plugin-svelte#218]
I'm currently getting an npm error when I try to include this in a project that uses svelte 5 because I think npm needs to specifically be told to add beta tags: https://classic.yarnpkg.com/en/docs/dependency-versions#toc-pre-release-tags

**Comment by webJose** [comment]
I believe I'm also in need of this.

**Comment by kling90** [comment]
Same here, Svelte 4 is installed in our packaged build environment because of the this peer dependency

![image](https://github.com/user-attachments/assets/fc55b675-d490-4fe4-81c2-9769cc33a30a)

This causes warnings at build time

![image](https://github.com/user-attachments/assets/74c097e7-2efb-4156-8868-ddd00dc7d5ce)

And this error in the application
```
Your application, or one of its dependencies, imported from 'svelte/internal', which was a private module used by Svelte 4 components that no longer exists in Svelte 5. It is not intended to be public API. If you're a library author and you used 'svelte/internal' deliberately, please raise an issue on https://github.com/sveltejs/svelte/issues detailing your use case.
```

We still need support for Svelte 4 though since we still got legacy apps using the same build environment.

**Comment by benmccann** [comment]
This is only an issue with the beta. The warning will go away once the final version is released

**Comment by josdejong** [comment]
It would be really helpful to me if `rollup-plugin-svelte` would support the current release candiates of svelte 5 too. 

Is it an option to define the peerDependency similar to [`svelte2tsx`](https://github.com/sveltejs/language-tools/blob/master/packages/svelte2tsx/package.json#L45-L48), like the following example?

```json
"peerDependencies": {
  "svelte": "^3.5.0 || ^4.0.0 || ^5.0.0-next.0 || ^5.0.0"
}
```

Or, to support future major versions too, add an entry for major release candidates: `">=3.5.0 || >=5.0.0-next"`.

**Comment by benmccann** [comment]
This should no longer be an issue now that there's been a final release

https://github.com/sveltejs/rollup-plugin-svelte/blob/c75899a0e3428e0795f21b8c54b55b540b460a63/package.json#L33
