### ISSUE TITLE
Use this.emitFile to output css

### ISSUE THREAD

**Issue by shirotech** [sveltejs/rollup-plugin-svelte#71]
https://github.com/rollup/rollup-plugin-svelte/blob/f8e8fa15e5cdf87847a2b02a5471f9f4481f8edb/index.js#L297

Saw this comment, I have been using this and I think it's relevant to that comment.

```js
generateBundle() {
  this.emitFile({type: 'asset', fileName: 'some-file.scss', source: sourceCode});
},
```

More info here, https://rollupjs.org/guide/en/#thisemitfileemittedfile-emittedchunk--emittedasset--string hope this helps.

**Comment by shirotech** [comment]
Have made a PR https://github.com/rollup/rollup-plugin-svelte/pull/72

**Comment by download13** [comment]
#72 seems to make the `CssWriter.write()` function emit files from rollup instead of writing them directly to the filesystem, but I'd like to clarify exactly what the behavior should be.

If the files get emitted instead of written directly, I think it might change the path they are written to, which would change the behavior of existing code which means pushing a new major version. For example, if I had an output config like `{ dir: 'dist' }` and a css option like `css => css.write('dist/styles.css')`. Under the old system styles would get written to `dist/styles.css` but with the new emitter they would instead be written to `dist/dist/styles.css`

Maybe we should leave the `CssWriter.write` method's behavior the same and add a method like `emit` so people can opt into the new way of doing things. We could deprecate `.write` and remove it at the next major version (unless there's a good reason to keep it). An option on `emit` that lets you choose whether to bundle the CSS or emit individual files would be good as well.
